version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - model
      - backend

  model:
    build: ./model
    ports:
      - "5002:5002"

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
